name: Build Netcat for ARMv7

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: 设置交叉编译环境
      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf make autoconf libtool

      # Step 3: Clone Netcat repository
      - name: Clone Netcat repository
        run: git clone https://github.com/diegocr/netcat.git

      # Step 4: Configure for ARMv7
      - name: Configure for ARMv7
        working-directory: netcat
        run: ./configure --host=arm-linux-gnueabihf

      # Step 5: Build Netcat for ARMv7
      - name: Build Netcat for ARMv7
        working-directory: netcat
        run: make

      # Step 6: Save ARMv7 binary
      - name: Save ARMv7 Binary
        working-directory: netcat
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp src/nc $GITHUB_WORKSPACE/artifacts/nc-armv7

      # Step 7: Upload the ARMv7 binary as a build artifact
      - name: Upload ARMv7 binary
        uses: actions/upload-artifact@v3.0.1
        with:
          name: nc-armv7
          path: $GITHUB_WORKSPACE/artifacts/nc-armv7
