name: Build Netcat for ARMv7

# 设置为手动触发工作流
on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 步骤1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2: 设置交叉编译工具链
      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf make autoconf libtool

      # 步骤3: 克隆并进入 Netcat 源码仓库
      - name: Clone Netcat repository
        run: |
          git clone https://github.com/diegocr/netcat.git
          cd netcat

      # 步骤4: 配置编译环境为 ARMv7
      - name: Configure for ARMv7
        run: |
          cd netcat
          ./configure --host=arm-linux-gnueabihf

      # 步骤5: 编译 Netcat
      - name: Build Netcat for ARMv7
        run: |
          cd netcat
          make

      # 步骤6: 保存编译结果
      - name: Save ARMv7 Binary
        run: |
          cd netcat
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp src/nc $GITHUB_WORKSPACE/artifacts/nc-armv7

      # 步骤7: 上传二进制文件作为构建产物
      - name: Upload ARMv7 binary
        uses: actions/upload-artifact@v3
        with:
          name: nc-armv7
          path: $GITHUB_WORKSPACE/artifacts/nc-armv7
