name: Build Ncat for ARMv7

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 步骤1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2: 安装交叉编译工具链
      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf make autoconf libtool

      # 步骤3: 克隆并进入 Ncat (Netcat) 仓库
      - name: Clone Ncat repository
        run: |
          git clone https://github.com/nmap/ncat.git
          cd ncat

      # 步骤4: 运行配置脚本
      - name: Configure Ncat for ARMv7
        run: |
          cd ncat
          ./configure --host=arm-linux-gnueabihf

      # 步骤5: 编译 Ncat
      - name: Build Ncat for ARMv7
        run: |
          cd ncat
          make CC=arm-linux-gnueabihf-gcc  # 使用交叉编译器进行编译

      # 步骤6: 保存编译结果
      - name: Save ARMv7 Binary
        run: |
          cd ncat
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp src/ncat $GITHUB_WORKSPACE/artifacts/ncat-armv7

      # 步骤7: 提交二进制文件到仓库
      - name: Commit and push ARMv7 binary to repository
        run: |
          cd $GITHUB_WORKSPACE
          # 添加二进制文件到 git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add artifacts/ncat-armv7
          git commit -m "Add ARMv7 binary for Ncat"
          git push origin HEAD:main  # 或者推送到其他分支
