name: Build Netcat for ARMv7

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up cross-compilation environment
      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf make autoconf libtool

      # Step 3: Clone and navigate to Netcat source repository
      - name: Clone Netcat repository
        run: |
          git clone https://github.com/diegocr/netcat.git
          cd netcat

      # Step 4: Configure for ARMv7
      - name: Configure for ARMv7
        run: |
          cd netcat
          ./configure --host=arm-linux-gnueabihf

      # Step 5: Build Netcat
      - name: Build Netcat for ARMv7
        run: |
          cd netcat
          make

      # Step 6: Save ARMv7 binary
      - name: Save ARMv7 Binary
        run: |
          cd netcat
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp src/nc $GITHUB_WORKSPACE/artifacts/nc-armv7

      # Step 7: Upload the ARMv7 binary as a build artifact
      - name: Upload ARMv7 binary
        uses: actions/upload-artifact@v3  # Use v3 for upload-artifact action
        with:
          name: nc-armv7
          path: $GITHUB_WORKSPACE/artifacts/nc-armv7
